### ISSUE TITLE
Feature Request: Label Spawn Positions

### ISSUE THREAD

**Issue by Datachange** [imaginary-png/HuntHelper#11]
First off, I love this tool!

Here is my enhancement request:
When searching for particular A/B hunts, it is helpful to know which spawn points are associated with which hunt. I would think having a way to label the spawn points with which hunt they are associated with would be a major boon to this already fantastic tool. Maybe color code the dots? Maybe actual text labels? I'll leave that design up to you.

Thank you very much!

**Comment by imaginary-png** [comment]
I don't plan on adding this as lots of hunts spawn the same positions and IMO it would make things unnecessarily visually busy.

If you check the spawn data here, http://cablemonkey.us/huntmap2/

You'll see each individual hunt (A, B, and S) have a lot of cross-over spawn spots.
