### ISSUE TITLE
Feature Request: ability to manually mark spots in the recording

### ISSUE THREAD

**Issue by Jaksuhn** [imaginary-png/HuntHelper#18]
If I'm trying to narrow down S rank spots with others, I have to be nearby the kill for hunthelper to detect. Or if I join someone midway through trying to narrow down, it would be nice to be able to simply add their data.

**Comment by imaginary-png** [comment]
That's what the export feature is for  
![image](https://user-images.githubusercontent.com/70348218/188776420-bd4206d2-cb3a-4f08-8725-df53e611af6f.png)  

Unless you mean in real-time, which would require some kind of server or other type of connection between clients, which I'm not going to do.

**Comment by Jaksuhn** [comment]
By "it would be nice to able to simply add their data", I did not mean that they also had HuntHelper. Just if someone told me "I already confirmed spot x20,y16 had a B rank killed on it". I'm not picturing this as a connection between clients, I just mean if it was possible to just, let's say, right click on a spawn point and hit "mark" so it turns red.

**Comment by imaginary-png** [comment]
Ok yeah, that makes more sense. My first response would be to tell them to use HuntHelper LOL.

But I could see this being useful if they're on console or something. I'll take a look into it.

**Comment by imaginary-png** [comment]
I've pushed an update through, waiting on it to be accepted by the Dalamud team.  

I added the ability to toggle if a spawn point is taken by double clicking on it via the map. This requires that recording is enabled in the spawn point refinement window.

I only tested it real quick on two maps, so lmk if there's any issues.
