### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by skylargraves** [imaginary-png/HuntHelper#20]
I've tried over the past few weeks or even longer to see if this will finally load up but doesn't seem to be the case. It's install just gives the error failed to load. I've done some trouble shooting in the past and disabled all others with no success. Any ideas for this? At the risk of being passed off to someone else not interested in helping with third party stuff I do run on a MacBook pro.

**Comment by imaginary-png** [comment]
Yeah, sorry this plugin won't work on mac. It currently requires some Windows specific stuff to work, and I don't have a mac to test on so it would be a bit hard to rework.

**Comment by alercah** [comment]
I'm on Linux and I would like some as the functionality as well. Would it be possible for the plugin to simply skip out on Windows-specific functionality on other platforms?

**Comment by imaginary-png** [comment]
@alercah @skylargraves 

Someone made a PR that seems to have fixed things for unix systems, I've added the version under plugin testing. If you install HuntHelper via /xlplugins and right click on it, check this option and install to testing version. LMK if there are any issues with it.

![image](https://user-images.githubusercontent.com/70348218/216802899-cf2e3104-ad19-446b-af48-90f6e0719b99.png)
