### ISSUE TITLE
Massive FPS drop while in zone while an S-Rank is alive

### ISSUE THREAD

**Issue by Krojack** [imaginary-png/HuntHelper#23]
This just started happening out of the blue. Not sure how to trouble shoot. Took me a bit to even find out it was HH that was causing it.

The second I enter a zone that has an S-rank up my FPS drops to 3. I teleport out of the zone (It's a struggle) FPS goes back to normal.
If I alt-tab to my web browser it goes back to normal. Back into the game it drops back to 3.
Right when the S-Rank dies my FPS goes back to normal.
Today, I tried disabling mods. First Sonar... didn't fix. Then I disabled HH and BAM my FPS went back to normal.

This wasn't happening a week ago while having HH enabled and killing S-Ranks. I have not installed any other mods between then and now either. The only changes I know of were to the XIVLauncher but I don't think they would be linked to this. I don't know the details so can't say.

Just tested with an A-Rank mob. Same thing but ONLY when in range of the the mob and when it NOT on my screen. If I turn around so it's behind me then my FPS drops to 3. Rotate camera back around so it's in front of me and FPS go back to normal.

The one thing that did change is I updated to the latest Nvidia drivers. I wanted them for the new RTX Super resolution with browser video upscaling but that's limited to web browsers only...

Update: So in HH settings I disabled the "Visual Help" under "Notifications" for both "A" and "S" ranks and now my FPS remains fine.  Something with this is killing the FPS all of a sudden while out of the mobs visual range or the mob is off your screen. I don't have the visual help enabled for B-ranks and they didn't have an FPS problem so that made me disable it for the 'A' and 'S' ranks.

**Comment by imaginary-png** [comment]
Weird, I can't seem to reproduce this with Visual Help enabled and looking away from an A and B rank. 
The last time HH was updated was 3 weeks ago, and that was just a minor update that shouldn't be related to this feature at all.

Can you try restarting your PC just in case something's gone wonky?

If that doesn't fix it, can you check task manager when it's happening? 

If it started immediately after updating drivers, I guess that could somehow be related. Not too sure lol.

**Comment by Krojack** [comment]
It was happening last night which was the first time I ran into it and today. Did a restart last night while trying to track it down and been another restart between last night and today.

I did check task manager last night to see if FF14 process CPU usage changed and it didn't. The ONLY thing that changes is the GPU usage just goes to 0% load.

Next step is to try a driver rollback but I can't do that at the moment. I will report back if that changes anything. I'll try that later today. 

Current Nvidia driver installed: 531.18 (release 02/28/2023)

**Comment by Krojack** [comment]
Rolled back to Nvidia Driver 528.49 same thing. I'll go back to 528.24 later. I can't recall which one of those I was on before updating. I'm also use it's not Hunt Helper at this point.

I did notice one more thing. When the Visual Help image is on the left hand side of the screen (when the mob is off to the left off your screen) the image is also on my second monitor screen. At this point the FPS is still fine. It's when that image is off my second display is when the FPS drops to 3. Screenshot below of how it shows up on my second display.

So when that visual help image is along the top, right, or bottom edge of my primary display is when the FPS drops.

This is so weird.

![image png](https://user-images.githubusercontent.com/908461/222993212-86cfa98b-6aa3-4fe9-8c4c-2ddab1977ee5.jpg)

**Comment by Krojack** [comment]
Last post on this for the time being. I sorta have it working to the point where it doesn't break my game.

I made some adjustments in the Nvidia Control Panel under Manage 3D settings just for the FF14 game.

Max Frame Rate => 120 (because I personally don't notice anything over this and it makes my computer run more quiet)
Vertical sync => Off (was set to use application setting but we all know vsync is evil on high end computers)

Also if I change the game to run in full screen mode none of this happens and the Visual Helper image stays only within the game window. This is a no go for me though. I would rather disable the visual helper.

I'm going to do more playing around with the Nvidia control settings (when I get time) for the game to see if I can narrow this down more. If you wish I can report back my findings. If not feel free to close this.

**Comment by imaginary-png** [comment]
Okay I was confused for a bit about how it was drawing outside of the game, but I assume it's because you have 'Enable multi-monitor windows' enabled in the Dalamaud settings because otherwise it shuoldn't be possible

After enabling it and playing around with it, unfortunately I still can't reproduce it.

Since the drop seems to happen when it's off the game screen, disabling the multi-monitor windows option should fix it? Assuming you don't use it.

I'm personally on driver ver. 516.94.

If you work out the issue, I'd love to know.

**Comment by Krojack** [comment]
'Enable multi-monitor windows' enabled in the Dalamaud settings

It was on and I don't ever recall turning it on. Been using it so long though. Either way I turned that off and it fixed everything.

So something with that image going off screen screws with some frame rate deal.

Thanks for the help!
