### ISSUE TITLE
[Feature Request] Could we get two more S ranks added to the counter functionality?

### ISSUE THREAD

**Issue by Wild-Carrot** [imaginary-png/HuntHelper#24]
Can we get a counter update for some more spawns, like **Nunyunuwi** (Southern Thanalan)? It'd be nice to know if any FATEs despawned and how close we are to 1 hour. If something like that is impossible, or just not worth the trouble, I get it.

**Bird of Paradise** (Sea of Clouds) could also have one. Many of us pull Squonk then go AFK, but it'd be nice to know how many Chirps actually went off. Unlike the other counters, though, this is not a guaranteed trigger, so I could see that as a reason to not bother.

**Comment by imaginary-png** [comment]
Done and done!

I've roughly tested the individual basic functionality but haven't actually done multiple fates in a row or anything, so let me know if anything's wonky.

Will push the update out today.
