### ISSUE TITLE
Gathering Counter Not Counting

### ISSUE THREAD

**Issue by somollya** [imaginary-png/HuntHelper#27]
I've seen this in multiple zones, but the gathering tracker does not increment when hitting the node. This is the case for both mining and botany. Example:

![image](https://github.com/imaginary-png/HuntHelper/assets/11787431/2552a979-ffa7-4d1b-b294-2efdc8c8c3a6)

**Comment by imaginary-png** [comment]
![image](https://github.com/imaginary-png/HuntHelper/assets/70348218/11db7034-7684-4fef-a42a-b0b9cc87af6f)

Works for me, try resetting your game to update dalamud.

**Comment by somollya** [comment]
This was also happening prior to the patch. Is there an associated plugin I need, similar to what was needed for using the teleport buttons?

**Comment by imaginary-png** [comment]
You need system messages enabled in the chat log
![image](https://github.com/imaginary-png/HuntHelper/assets/70348218/031de61d-a58c-46ea-ae0f-be7bd8cb76b0)

**Comment by somollya** [comment]
Weird, it's clearly something on my end but not sure what's up. I'll play around with different options, unless you have another idea. Thank you!

![image](https://github.com/imaginary-png/HuntHelper/assets/11787431/917ea9e2-c357-4d7f-82d1-b676ff804071)

**Comment by somollya** [comment]
Figured it out - this option has to be selected so that the log displays "You" instead of any form of abbreviated name:

![image](https://github.com/imaginary-png/HuntHelper/assets/11787431/320d9ec4-4543-423b-9e13-b4845d7b36c5)

Thank you!
