### ISSUE TITLE
How should I display the map?

### ISSUE THREAD

**Issue by Aforgomon** [imaginary-png/HuntHelper#29]
My english is not good,so it may be a little difficult to understand,I'm sorry
I checked the [Map Image],but i don't see any map,no matter where I am.I'm sure that the images was downloaded in my plugins folder, 41 photos in total.So could you show me how to display the map?
![2](https://github.com/imaginary-png/HuntHelper/assets/47466534/ab46cc52-6540-429d-bac9-a40c2657c9cb)
![1](https://github.com/imaginary-png/HuntHelper/assets/47466534/2ad08fd0-81da-4cb5-947f-f6089573f90b)

**Comment by Aforgomon** [comment]
My map opacity is -50,not completely transparent

**Comment by imaginary-png** [comment]
Can you show me the whole image: 
![image](https://github.com/imaginary-png/HuntHelper/assets/70348218/820940d5-ee0c-466f-99d9-3a70b74fcc98)

Also can you go to /xlplugins and disable HuntHelper: 
![image](https://github.com/imaginary-png/HuntHelper/assets/70348218/562f884b-81bc-4ee9-8cd3-9257d7a74ec3)

then open /xllog 

then enable HuntHelper and see if there are any error messages.
